name: Common Lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: daaa1k/common-lint@6a7517170a90fb3129892f9c8a6e6c37e82e3715 # v1.4.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
